node {
    def server = Artifactory.newServer "Artifactory"
    def rtGradle = Artifactory.newGradleBuild()

    stage 'Build'
        git url: 'https://github.com/jfrogdev/project-examples.git'

    stage 'Artifactory configuration'
        rtGradle.tool = GRADLE_TOOL // Tool name from Jenkins configuration
        rtGradle.deployer repo:'libs-release-local', server: server
        rtGradle.resolver repo:'libs-release', server: server

    stage 'Exec Gradle'
        def buildInfo = rtGradle.run rootDir: "gradle-examples/4/gradle-example-ci-server/", buildFile: 'build.gradle', tasks: 'clean artifactoryPublish'

    stage 'Publish build info'
        server.publishBuildInfo buildInfo
}